# Generated by Django 5.1.2 on 2024-10-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educador',
            name='dias_horas_preferidas',
            field=models.TextField(blank=True, default='todos:13-17', null=True),
        ),
    ]
