# Generated by Django 5.1.2 on 2024-10-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='usuario',
            new_name='estudante',
        ),
    ]
