# Generated by Django 5.1.2 on 2024-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_rename_usuario_aula_estudante'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(models.Q(('horario_inicio__gte', models.F('horario_inicio')), ('horario_inicio__lt', models.F('horario_fim'))), models.Q(('horario_fim__gt', models.F('horario_inicio')), ('horario_fim__lte', models.F('horario_fim'))), _connector='OR')), fields=('estudante', 'data_aula'), name='unique_aula_estudante_horario'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(models.Q(('horario_inicio__gte', models.F('horario_inicio')), ('horario_inicio__lt', models.F('horario_fim'))), models.Q(('horario_fim__gt', models.F('horario_inicio')), ('horario_fim__lte', models.F('horario_fim'))), _connector='OR')), fields=('educador', 'data_aula'), name='unique_aula_educador_horario'),
        ),
    ]
