# Generated by Django 5.1.2 on 2024-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_aula_unique_aula_estudante_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(),
        ),
    ]
