# Generated by Django 5.1.2 on 2024-10-19 09:44

import django.db.models.deletion
import sistema.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_aula_data_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eh_educador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='educador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aulas', to='sistema.educador'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='situacao',
            field=models.IntegerField(choices=sistema.models.get_situacoes_choices, default=0),
        ),
    ]
